name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Checkout wizthesis sources
      uses: actions/checkout@v2
      with:
        repository: karolbelina/wizthesis
        path: wizthesis
    - run: mv wizthesis/src/wizthesis.cls src
    - name: Build
      uses: xu-cheng/latex-action@v2
      with:
        post_compile: "latexmk -c"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: W08_242499_2020_praca_inżynierska
        path: out/W08_242499_2020_praca_inżynierska.pdf
    - name: Publish to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        publish_dir: out
